version: '3'
services:
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - "3308:3306"

  ticket_server:
    container_name: ticket_server
    build: ./server
    ports:
      - "8761:8761"
    expose:
      - "8761"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/serveur_service_qualite?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: serveur-service
      SERVER_PORT: 8761
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: "false"
      EUREKA_CLIENT_FETCH_REGISTRY: "false"

  ticket_gateway:
    container_name: ticket_gateway
    build: ./gate
    ports:
      - "8888:8888"
    expose:
      - "8888"
    environment:
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: Gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ticket_server:8761/eureka
    depends_on:
      - ticket_server


  ticket_client:
    container_name: ticket_client
    build: ./client
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/client_microserv_qualite?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: microservice-client
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ticket_server:8761/eureka
    depends_on:
      - ticket_server

  ticket_admin:
    container_name: ticket_admin
    build: ./admin
    ports:
      - "8083:8083"
    expose:
      - "8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/admin_service?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: admin-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ticket_server:8761/eureka
    depends_on:
      - ticket_server

  ticket_event:
    container_name: ticket_event
    build: ./admin
    ports:
      - "8082:8082"
    expose:
      - "8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/admin_service?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: admin-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ticket_server:8761/eureka
    depends_on:
      - ticket_server

  ticket_reservation:
    container_name: ticket_reservation
    build: ./reservation
    ports:
      - "8084:8084"
    expose:
      - "8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/admin_service?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_APPLICATION_NAME: admin-service
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://ticket_server:8761/eureka
    depends_on:
      - ticket_server
